create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  name text not null,
  target numeric not null,
  saved numeric not null default 0,
  progress numeric not null default 0,
  due text not null,
  reserved numeric,
  amount numeric
);

create table if not exists public.expenses (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  amount numeric not null,
  time text not null
);

create table if not exists public.saving_goals (
  id bigint generated by default as identity primary key,
  title text not null,
  target numeric not null,
  saved numeric not null default 0,
  progress numeric not null default 0,
  status text not null
);

create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  title text not null,
  amount numeric not null,
  date text not null
);

create table if not exists public.paylaters (
  id bigint generated by default as identity primary key,
  name text not null,
  months integer not null,
  monthly_payment numeric not null,
  total_amount numeric not null,
  image_url text
);

create table if not exists public.incomes (
  id bigint generated by default as identity primary key,
  source text not null,
  amount numeric not null,
  created_at text not null
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  profile_name text not null,
  email text not null,
  is_premium boolean not null default false,
  theme text not null,
  currency text not null default 'PHP',
  date_format text not null
);